export const incompatibleFonts = [
  "Allkin",
  "Chiron Sung HK",
  "Chiron GoRound TC",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons Outlined",
  "Material Icons",
  "Material Icons Round",
  "Material Icons Two Tone",
  "Material Icons Sharp",
  "Material Symbols",
  "Material Symbols Outlined",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU QLD",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD Guides",
  "Playwrite AU SA",
  "Playwrite AU SA Guides",
  "Playwrite AU TAS Guides",
  "Playwrite AU TAS",
  "Playwrite BE VLG",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL",
  "Playwrite BE WAL Guides",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CU",
  "Playwrite CZ",
  "Playwrite CU Guides",
  "Playwrite DE Grund",
  "Playwrite CZ Guides",
  "Playwrite DE LA",
  "Playwrite DE Grund Guides",
  "Playwrite CL",
  "Playwrite DE LA Guides",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES",
  "Playwrite DK Uloopet",
  "Playwrite ES Deco",
  "Playwrite ES Deco Guides",
  "Playwrite ES Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad",
  "Playwrite FR Trad Guides",
  "Playwrite GB J",
  "Playwrite GB S",
  "Playwrite GB S Guides",
  "Playwrite GB J Guides",
  "Playwrite HR Lijeva",
  "Playwrite HR",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU Guides",
  "Playwrite HU",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IE",
  "Playwrite IE Guides",
  "Playwrite IN Guides",
  "Playwrite IN",
  "Playwrite IS",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite NG Modern",
  "Playwrite MX",
  "Playwrite IT Trad Guides",
  "Playwrite MX Guides",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NZ",
  "Playwrite NO Guides",
  "Playwrite NZ Basic Guides",
  "Playwrite NZ Basic",
  "Playwrite NO",
  "Playwrite PE",
  "Playwrite NZ Guides",
  "Playwrite PE Guides",
  "Playwrite PL Guides",
  "Playwrite SK",
  "Playwrite RO Guides",
  "Playwrite RO",
  "Playwrite PT",
  "Playwrite PL",
  "Playwrite PT Guides",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite US Trad",
  "Playwrite US Trad Guides",
  "Playwrite US Modern Guides",
  "Playwrite TZ Guides",
  "Playwrite VN",
  "Playwrite US Modern",
  "Playwrite VN Guides",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Wavefont"
];